# Generated by Django 3.2.5 on 2021-12-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_score',
            new_name='score',
        ),
    ]
