# Generated by Django 3.2.9 on 2021-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0002_auto_20211202_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
