# Generated by Django 3.2.9 on 2021-12-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(),
        ),
    ]
