# Generated by Django 3.2.9 on 2021-12-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0005_auto_20211203_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
