# Generated by Django 3.2.9 on 2021-12-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0010_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
