# Generated by Django 3.2.5 on 2021-12-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0012_leaderboard_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
