# Generated by Django 3.2.9 on 2021-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0013_leaderboard_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games_played',
            field=models.FloatField(default=0),
        ),
    ]
