# Generated by Django 3.2.9 on 2022-03-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0014_user_games_played'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leaderboard',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
